//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchShop.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BANHANGEntities : DbContext
    {
        public BANHANGEntities()
            : base("name=BANHANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbdanhmuc> tbdanhmucs { get; set; }
        public virtual DbSet<tbsanpham> tbsanphams { get; set; }

        public System.Data.Entity.DbSet<WatchShop.DBContext.product> products { get; set; }

        public System.Data.Entity.DbSet<WatchShop.DBContext.Brand> Brands { get; set; }

        public System.Data.Entity.DbSet<WatchShop.DBContext.category> categories { get; set; }
    }
}
