//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchShop.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbdanhmuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbdanhmuc()
        {
            this.tbsanphams = new HashSet<tbsanpham>();
        }
    
        public int id { get; set; }
        public string tendanhmuc { get; set; }
        public string alias { get; set; }
        public string tieudeseo { get; set; }
        public string mota { get; set; }
        public string tukhoa { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public string hinhanh { get; set; }
        public Nullable<bool> top { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbsanpham> tbsanphams { get; set; }
    }
}
