//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchShop.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbsanpham
    {
        public int id { get; set; }
        public string tensanpham { get; set; }
        public Nullable<int> giaban { get; set; }
        public Nullable<int> giakm { get; set; }
        public string hinhanh { get; set; }
        public string alias { get; set; }
        public string tieudeseo { get; set; }
        public string mota { get; set; }
        public Nullable<bool> spmoi { get; set; }
        public Nullable<bool> spbanchay { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public Nullable<int> danhmucid { get; set; }
        public Nullable<bool> spgiamgia { get; set; }
    
        public virtual tbdanhmuc tbdanhmuc { get; set; }
    }
}
